### ISSUE TITLE
Add "refresh preset" button

### ISSUE THREAD

**Issue by FedericoMilesi** [decompme/decomp.me#1282]
**Is your feature request related to a problem? Please describe.**
I'm not exactly sure what happened, if it was some change done to maspsx or to the Legacy of Kain: Soul Reaver preset, but when accessing older 100% matching scratches that use $gp values, suddenly a lui instruction appears that bogs the matching percent down. Like in the following example scratch: https://decomp.me/scratch/S2xt6

The only way to fix this currently is to select another preset and then switch back to the Legacy of Kain: Soul Reaver one for the extra instruction to go away, but doing this repetitively like I am currently doing feels like a chore. 

**Describe the solution you'd like**
Some sort of "refresh" button next to the preset dropdown wouldn't be bad.

**Describe alternatives you've considered**
Being able to reselect the "Legacy of Kain: Soul Reaver" preset on the dropdown list and have it automatically update to the current configuration wouldn't be bad, either.

**Comment by mkst** [comment]
The reason for the scratch score changing is due to `maspsx` being updated to better differentiate between the different ASPSX versions.

The scratch you linked is passing `-Wa,--aspsx-version=2.79` but the updated preset passes `-Wa,--aspsx-version=2.81`.

We do not retroactively update scratch compiler flags when a preset is updated - it would end up overwriting any custom compiler flags a user might have changed (and therefore result in a scratch potentially no longer matching).

Selecting a different preset and selecting the correct preset again isn't a hugely different workflow to selecting the same preset again (2 extra clicks) so I'm going to close out this ticket as WONTFIX.
