### ISSUE TITLE
Hover-over timestamps are unfriendly

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#1331]
![image](https://github.com/user-attachments/assets/b13f1f03-e444-4762-b9d7-fd439b82e678)

It's good that we show the day and time. I think we can avoid showing a resolution beyond single seconds, though. and adding some spaces for readability would be ideal.

maybe just `2024-07-28 18:40:31 +09:00`

We should check to see if this is an issue in other places besides just the about scratch page, for good measure

**Comment by ankitjha420** [comment]
Hello, here's what I'd do to fix this issue ->
The hover-on text comes from the title of <time> so instead of:
<time datetime="2024-08-22T13:42:12.622Z" title="2024-08-22T22:42:12.622466+09:00">8 minutes ago</time>
We'll use:
<time datetime="2024-08-22T13:42:12.622Z" title="2024-08-22 22:42:12 +09:00">8 minutes ago</time>
If this looks okay can I be assigned this issue?

**Comment by mkst** [comment]
![image](https://github.com/user-attachments/assets/a19c341b-4809-4e51-9244-65fd4de954c7)

What am I missing?

**Comment by ankitjha420** [comment]
@mkst the time displayed on the hover-over is too detailed, the seconds part can just be an int instead of a float with 6 digits after the decimal point.

**Comment by ethteck** [comment]
You said "instead of 8 minutes ago, we'll use 8 minutes ago" - there was no difference between the two, so that was confusing. Also, the "x minutes ago" isn't the hover-over text. We just want to change the string format to the one I specified
