### ISSUE TITLE
.NET support (for Unity games and more)

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [decompme/decomp.me#1388]
Use ILSpy as the decompiler: https://github.com/icsharpcode/ILSpy
Planned to only support unobfuscated code

**Comment by encounter** [comment]
Are there existing decompilation projects for .NET games?

decomp.me backends are generally only added if there are projects that would use it, and people willing to maintain it.

**Comment by H-A-M-G-E-R** [comment]
idk

**Comment by H-A-M-G-E-R** [comment]
You can decomp-match only a single function so that the modified function can overwrite the existing function, making it useful for modders.

**Comment by ethteck** [comment]
It wouldn't make sense for people to spend time and work pursuing this just for the abstract idea of supporting .net with no actual user of the arch on the site. On top of the fact that it would serve no practical purpose, it wouldn't be testable since no one has come to us interested in working with their .net project on decomp.me. 

For that reason, and due to the lack of specific information here, I'm gonna close this. Cool idea, but like encounter said, we prefer to have tangible projects / people behind these efforts.

**Comment by H-A-M-G-E-R** [comment]
We'll re-open it when we find a .NET decomp project

**Comment by H-A-M-G-E-R** [comment]
I found a failed decomp project with no attempt at matching: https://github.com/tge-was-taken/Sonic4Ep1-WindowsPhone-Decompilation
