### ISSUE TITLE
(GBA) other versions of gcc not used in agbcc nor old_agbcc

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [decompme/decomp.me#1397]
Changing the compiler version as a last resort for matching if you can't get it to match even by changing the flags...
You can't tell what compiler a GBA game uses, agbcc is used in pokeemerald, while older GBA games sometimes use a compiler older than agbcc...

**Comment by mkst** [comment]
Do you have links to any such compilers?

**Comment by ethteck** [comment]
If you have a specific project or compiler version that warrants this, let's start there when the time comes

**Comment by H-A-M-G-E-R** [comment]
i think a different gcc version is needed to match https://github.com/H-A-M-G-E-R/mf/blob/main/src/sa_x.c#L1025

**Comment by ethteck** [comment]
It's a non-insubstantial amount of work to add new compilers to the site. While we're sometimes happy to add a few versions preemptively for the sake of completionism / getting things out of the way, there is a near-endless list of possible GCC versions games can be built with. Your best bet is to locally grab different versions and check them yourself. That way, you can request a specific version to be added.

Keep in mind, you'll need a reliable place this version is built if it's not an official release. agbcc has its own repo with CI that publishes releases, so I'm assuming you'd need to set up something similar

**Comment by H-A-M-G-E-R** [comment]
Perhaps GBA games use GCC versions slightly older or newer than gcc 2.9-arm-000512
Also, what compiler version is used in old-agbcc?

**Comment by H-A-M-G-E-R** [comment]
Also, it seems that Metroid Fusion has a gcc version without the prologue bugfix (Prevent unnecessary saving of the lr register to the stack)

**Comment by H-A-M-G-E-R** [comment]
However I don't know how to compile gcc 2.95.3 for GBA

**Comment by H-A-M-G-E-R** [comment]
Why there are a lack of variety of GBA compilers available in decomp.me?

**Comment by AngheloAlf** [comment]
As others have already told you, decomp.me is a collaborative tool and it is a secondary tool for the local decompilation work.

Adding new compilers is usually done because there's an **existing and active decomp project that uses said compiler**. People from said project work on getting their compiler to work on decomp.me. Nobody here is going to just add arbitrary compilers just for the sake of it, since it may increment maintenance burden of the website.

I strongly suggest you to try to figure out the compiler needed for the project you are working on before asking for it on github issues, even when not even yourself know what compiler you need. If you don't know how to find the correct compiler then you could ask for help in that regard first in the decomp.me discord server, somebody may be able to help you or redirect to somewhere else where you could get help finding the correct compiler.

**Comment by H-A-M-G-E-R** [comment]
I don't use di=iscord anymore because it's gotten much worse in 2024; i strongly suggest using revolt instead (open-source and it's always getting better): https://revolt.chat/
