### ISSUE TITLE
Deleting scratches

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#308]
~~Users should be able to archive their scratches as a pseudo-deletion option~~

Add a DELETE endpoint for scratches

**Comment by ethteck** [comment]
I've changed my mind on this. We should allow straight-up deletion (as well?).

**Comment by nanaian** [comment]
> as well?

Probably not needed. updating the issue

**Comment by ethteck** [comment]
I'm confused. I said "we should allow deletion as well" and then you said it's probably not needed but renamed the issue to just "Deleting scratches". So what is your intention here? 

Either way, I do think we should let users straight-up delete scratches. I guess archiving is not that important, since we can just add more support for how scratches can be viewed / organized down the line.
