### ISSUE TITLE
Support for MS-DOS and Open Watcom

### ISSUE THREAD

**Issue by malespiaut** [decompme/decomp.me#468]
Hello,

I would like to request support for MS-DOS using the Open Watcom compiler.

Best regards.

**Comment by ethteck** [comment]
Hello. Unfortunately, we're kinda a long way from supporting that platform because our asm-differ tool only supports certain architectures. Not to say it could never happen, but you'd need to first add support there.

Do you know of any decomp projects using this compiler / platform? I'd be curious what their workflow is and what kinds of tools they're using.

**Comment by malespiaut** [comment]
Hello,

Thank you for your fast and detailed answer.

I thought that the Godbolt decompiler was supporting Open Watcom, but upon inspection, this isn't the case.

The project https://github.com/dethrace-labs/dethrace is the only one I know that makes use of the Open Watcom compiler, but I can't say for sure that it's purely a decompilation project. It would be best to ask @dethrace-labs directly.

I'll keep an eye on that issue, in the meantime.

**Comment by OmniBlade** [comment]
Not public, but I'm aware of a project to binary match the original Command and Conquer windows binaries that used watcom 10.5. Workflow is using custom scripts to dump asm from IDA. Its helped a lot by the fact so much of the original code was released open source as part of the Command and Conquer remaster release, but there are lots of undocumented changes in the code from the original and code for Sole Survivor was not released.

**Comment by ethteck** [comment]
Done in #794
