### ISSUE TITLE
Hang on scratch page

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#535]
Rendering this page ~~sends the client JS into an infinite loop and crashes~~ takes so long to render the browser considers the page unresponsive: https://decomp.me/scratch/SKrcm

API: https://decomp.me/api/scratch/SKrcm

**Comment by ConorBobbleHat** [comment]
Hi! I think this may be caused by the scratch in question having a large (~750 lines scattered throughout) difference in context between it and its parent scratch. JSDiff doesn't seem particularly well optimized to handle large strings with many differences, causing the page to lock up as it attempt to work out what needs highlighted.

Switching to an alternate diffing implementation (I tested [fast-myers-diff](https://github.com/gliese1337/fast-myers-diff)) reduces the overhead of calculating the diff for SKrcm from on the scale of an hour to about two seconds, allowing the page to load normally.

**Comment by nanaian** [comment]
Brilliant work @ConorBobbleHat, thank you! I think there's a few things we could do now, then:
1. Use a faster diffing implementation (fast-myers-diff) #543
2. Perform context diffing in a web worker so it doesn't block rendering. (2 seconds is still unacceptable in the long-term)

**Comment by ConorBobbleHat** [comment]
> Perform context diffing in a web worker so it doesn't block rendering. 

that makes complete sense - if you're interested, I could make the switch in the PR I have open?

**Comment by nanaian** [comment]
If you want to have a stab at it, go ahead!

**Comment by ethteck** [comment]
Thanks for the investigation and work!
