### ISSUE TITLE
Investigate this scratch that broke the site

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#596]
Load it into a local instance and see if the same happens. If not, we'll have to test again on the live site during off hours
[obj_loop_stopwatchman.zip](https://github.com/decompme/decomp.me/files/10178575/obj_loop_stopwatchman.zip)

**Comment by ConorBobbleHat** [comment]
Hi!

I was able to succesfully reproduce this on a local setup; creating the scratch and then attempting to do anything with it hangs the site.

It looks like IDO 5.3 is hanging when given this scratch as an input, even outside of the site. 

Some weedwhacking later, a minimized snippet that exhibits the same behaviour:

repro.c:
```typedef unsigned char u8;
typedef unsigned short int u16;
typedef unsigned int u32;
typedef signed char s8;
typedef signed short int s16;
typedef signed int s32;
typedef float f32;

struct TempStruct8 {
 f32 unk0;
 f32 unk4;
 f32 unk8;
 f32 unkC;
 s8 unk10;
};

typedef struct Object {
 f32 y_position;
} Object;

void obj_loop_stopwatchman(Object *obj, s32 updateRate) {
    s32 index;
    struct TempStruct8 **sp48[1];
    void *racer;
    void *header;

     if(index != 0) {
        struct TempStruct8 ** temp = sp48[-3];
        index--;
        while(index >= 0) {
            if ((temp[index]->unk10 != 11) && (temp[index]->unk10 != 14) && (temp[index]->unk8 > 0.0)) {
                obj->y_position = temp[index]->unk0;
            }
            index--;
        }
    }
}
```

to compile (slash hang indefinitely):
`backend/compilers/ido5.3/cc -c -Xcpluscomm -G0 -non_shared -Wab,-r4300_mul -woff 649,838,712 -32 -O2 -mips1 -o repro.o repro.c`

[for what it's worth: when Ctrl-C'ing the hanging IDO prompt, it dies with the message:
`Fatal error in: /usr/lib/uopt  child died due to signal 2.`]

**Comment by ethteck** [comment]
Thanks @ConorBobbleHat! Super interesting. I guess it'd be useful to know if this happens with the latest ido recomp and if it happens in the original ido compiler with qemu-irix. And yeah Alex we do have timeouts on sandbox stuff, but it's probably too high

**Comment by ethteck** [comment]
Some other folks did some testing, and this happens on the original ido under qemu irix as well. It also seems to be extremely specific. Only index -3 into sp48 causes the issue. I think we should put a more explicit limit on compiler invocations, rather than just the one in the nsjail. Alternatively, we reduce the nsjail timeout from 30s to something more like 3s.

**Comment by simonlindholm** [comment]
Would also be nice if users were limited to only a single compilation at a time, with newer ones killing older ones. ("Newer" being defined according to timestamps sent by the client, so unlucky network conditions don't result in a newer request getting dropped.) Don't know if our sandboxing library allows cancellations in a simple way.

**Comment by ethteck** [comment]
Closing since the root cause has been investigated: ido bad

wrote two spinoff issues that could help with similar situations in the future
