### ISSUE TITLE
Have Next.js not die if backend is down

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#617]
We should handle all errors that might come from foreign services during SSR, including the Django API. e.g.

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/9429556/208423066-c7e347a1-4379-4ab9-9f3f-6f2f221105aa.png">

(This happens because on my development setup, when Django isn't running, Nginx replies with an HTML 404 error page. Next.js tries to parse this as JSON, and this error is not caught so we end up with a dev-facing error. I presume without debug mode the user gets an empty screen?)

In particular, we should revert back to an "offline" version of the page (that can also be shown when a client goes offline) that later might queue requests for when the connection to the API comes back up. The first implementation of this can be a generic error page similar to [down.html](https://github.com/decompme/decomp.me/blob/main/frontend/down.html).

**Comment by nanaian** [comment]
> Pages should hopefully still stay up, and we should maybe warn the user to not navigate away while the site is updating. Instead, pages insatntly change to this yucky error, and so all progress is lost. very unfortunate if you're editing a scratch

**Comment by mkst** [comment]
I had a look at this a couple of weeks ago but didn't get any further than adding a few `console.log()` statements to try and understand what was going on.

My current understanding of the problem (based on local testing in Docker):

1. Upon any user interaction with the codemirror panel (e.g. clicking), the front-end fires off a couple of api requests.
2. These requests are handled by SWR
3. These requests hit nginx which responds with an html page with status of 504 saying that the gateway is unavailable.
4. front-end tries to do `response.json()` which fails because it cannot parse the response (cos it's html not json)
5. rather than SWR being smart and quietly retrying a bunch of times with exponential backoff, it returns the error back to the front-end api callee
6. api callee sees that status was not OK and throws the error
7. website crashes

I tried to read about SWR and it seems that it has functionality to have custom retry handling (in fact we do use it (unsure how successfully?) on some other api endpoints). So we should look at this, and see how to gracefully handle the backend being down (e.g. should all things that call the API be ok to get a `null` response back for example?).

**Comment by ethteck** [comment]
Finished in #827 :)
