### ISSUE TITLE
Add clang (Switch) compiler support

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#75]
Questions:
* Are there multiple versions we should care about?
* What are the common flags?
* How is it invoked?
* What dependencies do we need to worry about?
* Do we build it as part of project setup, include / obtain binaries, or leave it up to the instance runner to provide the compiler?

**Comment by leoetlino** [comment]
> * Are there multiple versions we should care about?

Yes, different games can use different versions of LLVM. Even a single game can use several compiler versions because Nintendo's toolchain team is pretty good at staying up-to-date with upstream LLVM.

> * What are the common flags?

The target flags: `-target aarch64 -mcpu=cortex-a57+fp+simd+crypto+crc -fPIC -stdlib=libc++`

Games sometimes pass flags that affect codegen though, e.g. `-g` (debug info), `-mno-implicit-float`, `-O2` vs `-O3`, etc. Given the number of flags I'm not sure only offering presets is a good idea because you'd have 10 (versions) × 2 (optimization flags) × 2 (debug info flags) × 2 (float codegen flags) × ... possibilities.

> * How is it invoked?

Well it's Clang, so it has the same standard interface as GCC.

> * What dependencies do we need to worry about?

None (other than system libs). Official Clang binary builds statically link LLVM.

> * Do we build it as part of project setup, include / obtain binaries, or leave it up to the instance runner to provide the compiler?

While possible (unlike the vast majority of other decomp projects!), building Clang from source would take a significant amount of time because LLVM has a huuuuuuuuuuuuuge codebase. If you need Clang binaries I'd recommend just grabbing them from https://releases.llvm.org/ -- the LLVM project provides official pre-built releases for every version from 1.0 to the latest 12.0 (again a luxury that most decomp projects do not have!)
